# Site settings
title: Geoffroy Stolaric
titlepage: WEB dev. senior
email: geoffroy.stolaric@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  DÃ©veloppeur fullstack PHP & JavaScript.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://marmits.github.io" # the base hostname & protocol for your site
twitter_username: marmitscom
github_username:  marmits
linkedin_username:  marmitscom
codeurweb_url: "codeur-web.fr"
jsonresume_url: "cv"
# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
year: :year
